### ISSUE TITLE
search request failed (Debug: line 53 of /shadertoyBrowser/ShadertoyBrowser)

### ISSUE THREAD

**Issue by kium-one** [matthewwachter/td-shadertoy#1]
I created an API key and added it to the browser component, yet when I click on Search (pulse), nothing happens. The same issue is there with the Converter component, it does not load the new ID provided.
The console shows "search request failed (Debug: line 53 of /shadertoyBrowser/ShadertoyBrowser)"

TD 2020.25380

**Comment by kium-one** [comment]
Also, the searching on shadertoy is extremely slow these days, maybe it's related. E.g. this takes forever to load https://www.shadertoy.com/results?query=curl

**Comment by ghost** [comment]
@najiglass I found a simple fix for this, see my PR https://github.com/matthewwachter/td-shadertoy/pull/2
